menusData = {'меню 1.xlsx': {'menuRecipes': {'recipeProducts': {'буряк': 35,
                                                    'вода': 400,
                                                    'горошок конс.': 100,
                                                    'капуста': 100,
                                                    'картопля': 400,
                                                    'квашений огірок': 130,
                                                    'кукурузда конс.': 50,
                                                    'майонез': 50,
                                                    'молочна ковбаса': 200,
                                                    'морква': 50,
                                                    'олія': 10,
                                                    'сіль': 5,
                                                    'фасоля': 75,
                                                    'цибуля': 20},
                                 'totalRecipeData': {'totalRecipeCalories': 0,
                                                     'totalRecipePrice': 0,
                                                     'totalRecipeWeight': 0}}},
 'меню 2.xlsx': {'menuRecipes': {'recipeProducts': {'буряк': 35,
                                                    'вода': 400,
                                                    'капуста': 100,
                                                    'картопля': 940,
                                                    'морква': 100,
                                                    'олія': 50,
                                                    'сіль': 10,
                                                    'фасоля': 75,
                                                    'цибуля': 75},
                                 'totalRecipeData': {'totalRecipeCalories': 0,
                                                     'totalRecipePrice': 0,
                                                     'totalRecipeWeight': 0}}}}