productsData = {'борошно': {'calories': 200, 'netWeightPercent': 100, 'price': 50},
 'буряк': {'calories': 500, 'netWeightPercent': 95, 'price': 8},
 'вода': {'calories': 0, 'netWeightPercent': 100, 'price': 0},
 'горошок конс.': {'calories': 100, 'netWeightPercent': 70, 'price': 20.5},
 'гречка': {'calories': 60, 'netWeightPercent': 100, 'price': 30},
 'капуста': {'calories': 100, 'netWeightPercent': 90, 'price': 5},
 'картопля': {'calories': 250, 'netWeightPercent': 90, 'price': 20},
 'квашений огірок': {'calories': 30, 'netWeightPercent': 60, 'price': 11.1},
 'кукурузда конс.': {'calories': 135, 'netWeightPercent': 70, 'price': 30.2},
 'майонез': {'calories': 600, 'netWeightPercent': 100, 'price': 8},
 'молочна ковбаса': {'calories': 500, 'netWeightPercent': 50, 'price': 100},
 'морква': {'calories': 200, 'netWeightPercent': 95, 'price': 6.3},
 'олія': {'calories': 600, 'netWeightPercent': 10, 'price': 35},
 'сіль': {'calories': 0, 'netWeightPercent': 100, 'price': 0.1},
 'фасоля': {'calories': 400, 'netWeightPercent': 100, 'price': 9.5},
 'цибуля': {'calories': 300, 'netWeightPercent': 95, 'price': 5.2}}