productsDataDoc = {' ': {'calories': 0, 'price': 0},
 'буряк': {'calories': 500, 'price': 8},
 'вода': {'calories': 0, 'price': 0},
 'горошок конс.': {'calories': 100, 'price': 20.5},
 'капуста': {'calories': 100, 'price': 5},
 'картопля': {'calories': 250, 'price': 20},
 'квашений огірок': {'calories': 30, 'price': 11.1},
 'кукурузда конс.': {'calories': 135, 'price': 30.2},
 'майонез': {'calories': 600, 'price': 8},
 'молочна ковбаса': {'calories': 500, 'price': 100},
 'морква': {'calories': 200, 'price': 6.3},
 'олія': {'calories': 600, 'price': 35},
 'сіль': {'calories': 0, 'price': 0.1},
 'фасоля': {'calories': 400, 'price': 9.5},
 'цибуля': {'calories': 300, 'price': 5.2}}